import Env from '@ioc:Adonis/Core/Env'

export default Env.rules({
  PORT: Env.schema.number(),
  APP_KEY: Env.schema.string(),
  DB_URL: Env.schema.string(),
  REDIS_URL: Env.schema.string(),
  SMS_CLIENT_ID: Env.schema.string(),
  SMS_CLIENT_SECRET: Env.schema.string(),
  SMTP_HOST: Env.schema.string(),
  SMTP_PORT: Env.schema.number(),
  SMTP_USERNAME: Env.schema.string(),
  SMTP_PASSWORD: Env.schema.string(),
  APP_URL: Env.schema.string(),
  AWS_REGION: Env.schema.string(),
  AWS_ACCESS_KEY_ID: Env.schema.string(),
  AWS_SECRET_ACCESS_KEY: Env.schema.string(),
  S3_PRIVATE_BUCKET_NAME: Env.schema.string(),
  FB_APP_SECRET: Env.schema.string(),
  FB_APP_ID: Env.schema.string(),
  IG_APP_ID: Env.schema.string(),
  IG_APP_SECRET: Env.schema.string(),
  TWITTER_CONSUMER_KEY: Env.schema.string(),
  TWITTER_CONSUMER_SECRET: Env.schema.string(),
  TWITTER_BEARER_TOKEN: Env.schema.string(),
  APIFY_TOKEN: Env.schema.string(),
  APIFY_INSTAGRAM_STATS_ACTOR_ID: Env.schema.string(),
  APIFY_INSTAGRAM_SEARCH_FEED_ACTOR_ID: Env.schema.string(),
  FLUTTERWAVE_SEC_KEY: Env.schema.string(),
  S3_PUBLIC_BUCKET_NAME : Env.schema.string(),
})
